export const INCREMENT = 'INCREMENT';
export const INCREMENT_REQUEST = 'INCREMENT_REQUEST';
export const INCREMENT_FAILURE = 'INCREMENT_FAILURE';

export const DECREMENT = 'DECREMENT';
export const DECREMENT_REQUEST = 'DECREMENT_REQUEST';
export const DECREMENT_FAILURE = 'DECREMENT_FAILURE';

export const STARTTIMER = 'STARTTIMER';
export const STARTTIMER_REQUEST = 'STARTTIMER_REQUEST';
export const STARTTIMER_FAILURE = 'STARTTIMER_FAILURE';

export const STOPTIMER = 'STOPTIMER';
export const STOPTIMER_REQUEST = 'STOPTIMER_REQUEST';
export const STOPTIMER_FAILURE = 'STOPTIMER_FAILURE';

export const RESETTIMER = 'RESETTIMER';
export const RESETTIMER_REQUEST = 'RESETTIMER_REQUEST';
export const RESETTIMER_FAILURE = 'RESETTIMER_FAILURE';
