export const SUBMIT = 'SUBMIT';
export const SUBMIT_REQUEST = 'SUBMIT_REQUEST';
export const SUBMIT_FAILURE = 'SUBMIT_FAILURE';

export const TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';
export const TOGGLE_COMPLETE_REQUEST = 'TOGGLE_COMPLETE_REQUEST';
export const TOGGLE_COMPLETE_FAILURE = 'TOGGLE_COMPLETE_FAILURE';
