export const INCREMENT = 'INCREMENT';
export const INCREMENT_REQUEST = 'INCREMENT_REQUEST';
export const INCREMENT_FAILURE = 'INCREMENT_FAILURE';

export const DECREMENT = 'DECREMENT';
export const DECREMENT_REQUEST = 'DECREMENT_REQUEST';
export const DECREMENT_FAILURE = 'DECREMENT_FAILURE';

export const DOSOMETHING = 'DOSOMETHING';
export const DOSOMETHING_REQUEST = 'DOSOMETHING_REQUEST';
export const DOSOMETHING_FAILURE = 'DOSOMETHING_FAILURE';

export const ADDFIVE = 'ADDFIVE';
export const ADDFIVE_REQUEST = 'ADDFIVE_REQUEST';
export const ADDFIVE_FAILURE = 'ADDFIVE_FAILURE';

export const MINUSFIVE = 'MINUSFIVE';
export const MINUSFIVE_REQUEST = 'MINUSFIVE_REQUEST';
export const MINUSFIVE_FAILURE = 'MINUSFIVE_FAILURE';

export const MINUSTWO = 'MINUSTWO';
export const MINUSTWO_REQUEST = 'MINUSTWO_REQUEST';
export const MINUSTWO_FAILURE = 'MINUSTWO_FAILURE';

export const ADDTWO = 'ADDTWO';
export const ADDTWO_REQUEST = 'ADDTWO_REQUEST';
export const ADDTWO_FAILURE = 'ADDTWO_FAILURE';

export const RESET = 'RESET';
export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_FAILURE = 'RESET_FAILURE';
