export const INCREMENT = 'INCREMENT';
export const INCREMENT_REQUEST = 'INCREMENT_REQUEST';
export const INCREMENT_FAILURE = 'INCREMENT_FAILURE';

export const DECREMENT = 'DECREMENT';
export const DECREMENT_REQUEST = 'DECREMENT_REQUEST';
export const DECREMENT_FAILURE = 'DECREMENT_FAILURE';

export const DOSOMETHING = 'DOSOMETHING';
export const DOSOMETHING_REQUEST = 'DOSOMETHING_REQUEST';
export const DOSOMETHING_FAILURE = 'DOSOMETHING_FAILURE';
